services:
  postgres:
    image: postgres:17
    container_name: weather-app-postgres
    environment:
      POSTGRES_DB: weather_app
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: